name: CI/CD

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.3.6

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Build
      run: haxe build.hxml

    - name: Build Tests
      run: haxe test.hxml

    - name: Run Tests
      run: node dist/test.js

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/jewish-date.js
